name: Deploy dist to release branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build with Vite
        run: yarn build

      - name: Deploy dist to release branch
        run: |
          # Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Sauvegarde le build
          mv dist ../dist-temp

          # Branche orpheline “release”
          git checkout --orphan release
          git reset --hard
          git clean -fdx

          # Replace avec le contenu du build
          mv ../dist-temp/* .

          # Commit & push
          git add .
          git commit -m "Deploy build to release branch"
          git push --force origin release